name: CICD-PULL-REQUEST

on:
  pull_request:


jobs:
  trigger-mode:
    name: make test
    runs-on: ubuntu-latest
    outputs:
      trigger-mode: ${{ steps.get_trigger_mode.outputs.trigger_mode }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get trigger mode
        id: get_trigger_mode
        run: |
          echo "base_ref:${{ github.base_ref }}"
          echo "ref:${{ github.event.pull_request.head.ref }}"
          echo "ref:${{ github.event.pull_request.base.ref }}"
          echo "full_name:${{ github.event.pull_request.head.repo.full_name }}"
          echo "repository:${{ github.repository }}"
          echo "1234"
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head.sha }}
          TRIGGER_MODE=`bash .github/utils/utils.sh --type 6`
          echo $TRIGGER_MODE
          echo trigger_mode=$TRIGGER_MODE >> $GITHUB_OUTPUT

  make-test:
    needs: trigger-mode
    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
    runs-on: ubuntu-latest
    steps:
      - name: make test
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}

  check-image:
    needs: trigger-mode
    if: needs.trigger-mode.outputs.trigger-mode == '[docker]'
    runs-on: ubuntu-latest
    steps:
      - name: check image
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}

  check-helm:
    needs: trigger-mode
    if: needs.trigger-mode.outputs.trigger-mode == '[deploy]'
    runs-on: ubuntu-latest
    steps:
      - name: check helm
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}
